### ISSUE TITLE
Missing Properties on Type Typescript

### ISSUE THREAD

**Issue by goalkes** [fancyapps/ui#483] opened 2023-04-18 04:20 UTC
### Describe the bug

Hi i'm currently using this package and facing a problem where properties on Fancybox not found when using typescript.

```
Fancybox.show([
  {
    src: "https://www.w3.org/",
    type: "iframe",
    preload: false,
    width: 600,
    height: 300,
  },
]);
```

where properties `type` and `preload` not exists on Fancybox show data.

With error message from vscode `Type '{ src: string; type: string; width: number; height: number; preload: false; dragToClose: false; }' is not assignable to type 'userSlideType'.
  Object literal may only specify known properties, and 'type' does not exist in type 'userSlideType'`

### Reproduction

just add sample from official site and got problem

```
Fancybox.show([
  {
    src: "https://www.w3.org/",
    type: "iframe",
    preload: false,
    width: 600,
    height: 300,
  },
]);
```

### Additional context

Maybe you can add missing properties type to support that api options.

**Comment by fancyapps** [comment] 2023-04-18 05:02
Hi, Actually, the types are here - https://github.com/fancyapps/ui/blob/main/types/Fancybox/plugins/Html/Html.d.ts - I suspect TS doesn't find them. I would appreciate it if anyone could suggest how to help TS resolve this.

**Comment by fancyapps** [comment] 2023-11-15 11:20
I'm closing this because I can't reproduce it anymore. A TS bug may have been fixed.

**Closed by fancyapps** 2023-11-15 11:20 UTC
Labels: needs triage
