### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by alkosorukov** [fancyapps/ui#717] opened 2024-12-24 08:55 UTC
### Describe the bug

Our uikit written in react uses your carousel. When I try to run the test, I get the error: "Module C:/project/node_modules/@fancyapps/ui/dist/carousel/carousel.autoplay.esm.js:1 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@fancyapps/ui" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:"

The problem arises because of the Autoplay import
import { Autoplay } from "@fancyapps/ui/dist/carousel/carousel.autoplay.esm.js";

I downloaded your distribution from github to see how you get around this problem in your tests, but I see that you weren't writing tests). How do I import Autoplay correctly?

### Reproduction

import { Autoplay } from "@fancyapps/ui/dist/carousel/carousel.autoplay.esm.js";

**Comment by fancyapps** [comment] 2024-12-24 09:32
Hi. I'm closing this, because the problem is not with the code, but with your tools.

> shipped in a CommonJS package

This is wrong, it is perfectly valid ES6 code and there is no problem using, for example, Vitejs. And people are successfully using it in their Rect, Vue, Svelte, Angular etc projects. Here you can also find links to sample projects - https://fancyapps.com/resources/integration/

> but I see that you weren't writing tests

There are actually hundreds of tests that are run before generating files for the "dist" directory, but they are from a private repository.

Anyway, I rarely get such issue reports, but sometimes they do appear, and I'm tired of it, so please write what tooling you use and what versions so I can contact their authors and get them to fix their code.

**Closed by fancyapps** 2024-12-24 09:32 UTC
Labels: needs triage
