### ISSUE TITLE
Need Typescript Definition

### ISSUE THREAD

**Issue by dimaslanjaka** [fancyapps/ui#350] opened 2022-09-12 10:52 UTC
error on typechecking while used in typescript react

![Screenshot from 2022-09-12 17-50-43](https://user-images.githubusercontent.com/12471057/189635973-ee47c489-fb0d-4423-8cd2-a01f0981fd6d.png)

**Comment by faizanakram99** [comment] 2022-11-17 10:35
> Related: #243

Hey peter, good to see you here too :smile:

**Comment by fancyapps** [comment] 2022-11-17 10:58
Hi, v5 is around the corner, it is written in TS and will not only fullfill
many feature requests, but will also bring couple of suprises.

Janis

**Comment by fancyapps** [comment] 2023-03-12 12:08
Duplicate of #112

**Closed by fancyapps** 2023-03-12 12:08 UTC
