### ISSUE TITLE
Typescript Error: Type '"classes"' cannot be used to index type 'OptionsType'

### ISSUE THREAD

**Issue by steve3d** [fancyapps/ui#429] opened 2023-03-04 16:43 UTC
### Describe the bug

I'm using fancybox/ui version 5 with angular, from angular 13, angular are using typescript strict mode by default for new created projects. 

So with the strict mode on, with v5 there is a error: 
```
Error: node_modules/@fancyapps/ui/types/shared/Base/Base.d.ts:11:24 - error TS2536: Type '"classes"' cannot be used to index type 'OptionsType'.

11     cn<T extends keyof OptionsType["classes"]>(key: T): string;
                          ~~~~~~~~~~~~~~~~~~~~~~

```

for now I have to manually delete this line to continue my work.

Please check your source code, try enabling the `strict` mode in tsconfig.json you might see this error.

### Reproduction

any project with `strict` mode on 

### Validations

- [X] Read the [docs](https://fancyapps.com/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zetti-caletti** [comment] 2023-03-07 13:30
Have the same problem. Also in Angular with strictMode on.

**Comment by fancyapps** [comment] 2023-03-07 13:32
You can safely ignore that, it is just limitation of Typescript, it woks fine, but unfortunately produces that message.

**Comment by zetti-caletti** [comment] 2023-03-07 13:34
How can I ignore it? Typescript stops compiling the code.

**Comment by fancyapps** [comment] 2023-03-07 13:35
Interesting, because all JS files are already compiled by TS.

**Comment by zetti-caletti** [comment] 2023-03-07 13:38
Well maybe the library is not developed in strictMode. Libraries should always be developed in strictMode :)

**Comment by zetti-caletti** [comment] 2023-03-07 13:39
> Interesting, because all JS files are already compiled by TS. I will look for a workaround when I will have time.

Nice :+1:

**Comment by fancyapps** [comment] 2023-03-07 13:49
Maybe you can help :) The problem is here - 

```js
cn<T extends keyof OptionsType["classes"]>(key: T): string {
  ...
}
```

Method `cn` is just a shortcut that returns item from the `classes` option, for example, `this.cn("container")` is the same as `this.option("classes.container")`. It works fine and correctly provides autocomplete/autocorrect in IDE, but, as you can see, it produces warning. I could set type as `string`, but then I would loose autocomplete/autocorrect.

**Comment by zetti-caletti** [comment] 2023-03-07 13:59
Yes this is the correct line:
![image](https://user-images.githubusercontent.com/75048883/223443223-1573cf53-1901-4002-9623-7b7a369ad0f6.png)

I think the problem is, that OptionType is just a generic and is not exported. So Typescript does not know, that there is a key called "classed" on this Type. Maybe you just have to import OptionType in Base.d.ts.

![image](https://user-images.githubusercontent.com/75048883/223443679-c2988d46-b5f5-4343-a2e1-e0b870d9f43a.png)

**Comment by zetti-caletti** [comment] 2023-03-07 14:01
I mean, right now, for Typescript OptionsType is not imported and is just a generic. And because it doesn't have type any it complains about the "classes" index.

**Comment by zetti-caletti** [comment] 2023-03-07 14:03
This, for example, works.

![image](https://user-images.githubusercontent.com/75048883/223444894-85aadc64-28e2-4b9c-b139-0a591a6095ea.png)

**Comment by zetti-caletti** [comment] 2023-03-07 14:15
I would just make ts-ignore. Now my Angular code compilies:

![image](https://user-images.githubusercontent.com/75048883/223448097-26ff3fd3-e07e-4f9c-926b-5d6c4e211399.png)

**Comment by zetti-caletti** [comment] 2023-03-07 14:16
> Yes, because then base interface is required everywhere and that is what I wanted to avoid :/

Understand

**Comment by zetti-caletti** [comment] 2023-03-07 14:22
Would be nice to do that in a minor update. Because my ts-ignore now is only local and manually edited. If I install it freshly the error will come again.

**Comment by fancyapps** [comment] 2023-03-07 14:27
You know, I have ts-ignore in the source code, too :). It simply was not appended to generated types. I will think about the solution for the next release.

**Comment by zetti-caletti** [comment] 2023-03-07 14:47
> 

Oh didn't knew. Maybe it works to append it to generated types.

**Comment by TheLexI** [comment] 2023-03-11 21:21
minimal fix
![image](https://user-images.githubusercontent.com/23502999/224512049-276400aa-638d-4914-99e0-931571bdf80f.png)

**Comment by fancyapps** [comment] 2023-03-12 08:02
Hi,

It should be fixed in the latest release. Thanks for reporting!

**Closed by fancyapps** 2023-03-12 08:02 UTC
