### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by simonittensammer** [fancyapps/ui#487] opened 2023-04-25 06:23 UTC
### Describe the bug

I'm trying to run an angular application (v14.1.3) using the Fancybox (v5.0.16) and I can't get it to work.

Every time I run `yarn start`, the following error occurs:
```
Error: node_modules/@fancyapps/ui/types/shared/Base/types.d.ts:4:116 - error TS2589: Type instantiation is excessively deep and possibly infinite.

4     [K in Extract<keyof O, string>]: O[K] extends Array<any> ? K : O[K] extends Record<string, unknown> ? `${K}` | `${K}.${DeepKeyOf<O[K]>}` : K;
```

I can't find any additional types, or similar, I need to install.

### Reproduction

media.component.html:
```
<p>
  <a data-fancybox="gallery" href="https://lipsum.app/id/60/1600x1200">
    <img src="https://lipsum.app/id/60/200x150" width="200" height="150" />
  </a>
  <a data-fancybox="gallery" href="https://lipsum.app/id/61/1600x1200">
    <img src="https://lipsum.app/id/61/200x150" width="200" height="150" />
  </a>
  <a data-fancybox="gallery" href="https://lipsum.app/id/62/1600x1200">
    <img src="https://lipsum.app/id/62/200x150" width="200" height="150" />
  </a>
  <a data-fancybox="gallery" href="https://lipsum.app/id/63/1600x1200">
    <img src="https://lipsum.app/id/63/200x150" width="200" height="150" />
  </a>
  <a data-fancybox="gallery" href="https://lipsum.app/id/64/1600x1200">
    <img src="https://lipsum.app/id/64/200x150" width="200" height="150" />
  </a>
</p>
```

media.component.ts:
```
import { Fancybox } from '@fancyapps/ui';

@Component({
  selector: 'app-media',
  templateUrl: './media.component.html',
  styleUrls: ['./media.component.scss'],
})
export class MediaComponent implements OnInit, OnDestroy {
  constructor(
    private elRef: ElementRef
  ) {
  }

  ngOnInit() {
    Fancybox.bind(this.elRef.nativeElement, '[data-fancybox]', {
      // Custom options
    });
  }

  ngOnDestroy() {
    Fancybox.unbind(this.elRef.nativeElement);
    Fancybox.close();
  }
}

```

### Additional context

The error occurs with every version v5.x.x of fancyapps.

**Comment by fancyapps** [comment] 2023-04-25 06:52
I wonder why it works perfectly fine for me, you can observe it here, too - https://stackblitz.com/edit/angular-f6wtw1?file=angular.json,package.json And I do not see any issue with that particular code.

**Comment by simonittensammer** [comment] 2023-04-25 13:17
Yeah, It's weird. This stackblitz example is where I got the code from.

**Comment by fancyapps** [comment] 2023-11-15 11:22
I'm closing this because I can't reproduce it anymore. A TS bug may have been fixed.

**Closed by fancyapps** 2023-11-15 11:22 UTC
Labels: needs triage
