### ISSUE TITLE
appendSlide when using thumbs

### ISSUE THREAD

**Issue by morrow95** [fancyapps/ui#482] opened 2023-04-18 03:47 UTC
Using the carousel with the thumbs plugin the format for a slide is as so according to examples : 

```
<div class="f-carousel__slide" data-thumb-src="/someimage.jpg">
          <img src="/someimage.jpg" alt="something"/>
</div>
```

From my testing the thumbs will not show or work without the `data-thumb-src` value given in the containing `f-carousel__slide` div.  So, how are we supposed to supply that when appending a slide since we only insert the actual slide content and not the containing div with it?

```
carousel.appendSlide('<img class="img-fluid" src="/someimage2.jpg" alt="something2"/>');
```

**Comment by fancyapps** [comment] 2023-04-18 05:03
Hi,

Sorry, but syncing thumbnail elements with the main carousel is not yet implemented.

**Comment by morrow95** [comment] 2023-09-06 15:30
Any idea when this will be added in?  Or if there is another way to get around it when using 'appendSlide'?

**Comment by fancyapps** [comment] 2023-11-05 09:43
Duplicate of #71

**Closed by fancyapps** 2023-11-05 09:43 UTC
Labels: enhancement
