### ISSUE TITLE
Gallery view messes with browser navigation

### ISSUE THREAD

**Issue by pinksharpii** [fancyapps/ui#594] opened 2023-12-05 01:45 UTC
### Describe the bug

When you browse a gallery in a lightbox and then close it out and then click back on the browser, there is a duplicate link in the browser history.

### Reproduction

https://js-vbsiey.stackblitz.io/
You can view this behavior in an example.
Click on a slide.
Click on the X or background to close the lightbox.
Click the back button on your browser.
You don't go anywhere because it's adding the link to the browser history but not taking it out when you close out.

**Comment by fancyapps** [comment] 2023-12-05 07:07
Duplicate of #264

**Closed by fancyapps** 2023-12-05 07:07 UTC
Labels: needs triage
