### ISSUE TITLE
Slideshows aren't waiting for videos anymore

### ISSUE THREAD

**Issue by sjd23** [fancyapps/ui#664] opened 2024-06-19 22:45 UTC
### Describe the bug

The slideshow continues when there is html5 video playing. I found this comment where it was stated that this is not a problem anymore, and the old jsfiddle provided seems to support that idea. This is not the case with 5.0:

"Hi,

Slideshow now waits for html5 video to end (starting from v3.4.1)"

https://github.com/fancyapps/fancybox/issues/1983#issuecomment-417657084

### Reproduction

Add an html5 video to a gallery and press the slideshow's play button

**Comment by fancyapps** [comment] 2024-06-20 07:59
Duplicate of #246

**Closed by fancyapps** 2024-06-20 07:59 UTC
Labels: needs triage

**Comment by sjd23** [comment] 2024-06-20 12:48
While true, it doesn't call out that this was a feature intentionally added
a while back that isn't working right now.  So it's either a bug or
something someone intentionally removed and could hopefully speak to,
right?
